### PR TITLE
24170 - Dealer Staff Review Updates

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:*
https://github.com/bcgov/entity/issues/24170

*Description of changes:*
- Minor styling update to Launch Tiles
- Include Dealer Address in Staff Dealer Review
- Include additional Dealer requirements in Staff Dealer Review 

*Note* - Synced P-Lock file 
(was out of sync somehow - hence my million commits - had to go down to node 16.4.2 to sync)

Screenshot 2024-11-14 at 9 18 18 AM

Screenshot 2024-11-14 at 9 18 03 AM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-account-dev--pr-3145-i6czyyqd.web.app

**Review by seeker25 — APPROVED** [review]
LGTM

**Comment by seeker25** [comment]
Should be node 20.5.1?

**Comment by cameron-eyds** [comment]
> Should be node 20.5.1?
> 
> https://github.com/bcgov/sbc-auth/blob/3f839b294cdb9812f4f58327b5404981e8b57ae5/auth-web/Dockerfile#L1

Totally, i dunno what was up, as you can see by my commit count 😆.

Reverted back up after syncing and did a final `npm i`, got er in the end.
I think the package-lock wasn't updated in a previous commit to reflect the updated fas-ui versions, either way, all good!

**Comment by seeker25** [comment]
@cameron-eyds pushing to test, 10-15m

**Comment by cameron-eyds** [comment]
> @cameron-eyds pushing to test, 10-15m

Cool thanks sir, no rush at all!

**Pull request merged**
