### PR TITLE
Search by username on transaction view#4341

### PR DESCRIPTION
**Pull request by nitheesh-aot**
*Issue #:*
https://github.com/bcgov/entity/issues/4341

*Description of changes:*
- Added username search in transaction view
- Moved DateRange filter to a separate component and used that inside the Search Filter component.
- More flexibility in filter component
- Code clean up

*Checklist:*
I confirm that below checklist items are addressed in this pull request; (check the boxes applicable)
- [ ] No lint errors
- [ ] No test case failures and proper coverage for all modules/classes
- [ ] Updated the deployment configs for new environment variable(s)
- [ ] Updtaed the postman collection in entity repository (https://github.com/bcgov/entity/tree/master/api-e2e/postman) for e2e tests

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

### CODE REVIEW

**Comment by nitheesh-aot** [comment]
Apologies for the long PR, its basically moving the existing code from a large component to make it simpler and reusable.

**Review by saravanpa-aot — APPROVED** [review]

**Comment by sumesh-aot** [comment]
Is test cases coming as new PR ?

**Comment by saravanpa-aot** [comment]
do wait for one more approval please

**Comment by nitheesh-aot** [comment]
> Is test cases coming as new PR ?

Yes, will have a new PR for that

**Pull request merged**
