### PR TITLE
17384 Auth Web - Action menu button state issue

### PR DESCRIPTION
**Pull request by chenhongjing**
*Issue #:*
https://github.com/bcgov/entity/issues/17384

*Description of changes:*
- Fix action button menu state issue
- App version=2.4.5

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-account-dev--pr-2527-m48vzcs6.web.app

**Review by seeker25 — APPROVED** [review]
Thank you for this

**Review by severinbeauvais — COMMENTED** [review]
LGTM

**Pull request merged**
