### PR TITLE
17327 & 17856 - Add in overdue to the transactions table & fix status for Online Banking

### PR DESCRIPTION
**Pull request by seeker25**
*Issue #:*
https://github.com/bcgov/entity/issues/17327
https://github.com/bcgov/entity/issues/17856

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

### CODE REVIEW

**Review by ochiu — APPROVED** [review]
Looks good

**Comment by seeker25** [comment]
image

**Comment by seeker25** [comment]
I showed Ethan the screenshot, didn't hear anything of concern

**Comment by seeker25** [comment]
UX provided via screenshots, Ethan made some suggestions and I executed them

**Review by ochiu — APPROVED** [review]

**Pull request merged**
