### PR TITLE
17493 - Caching issues

### PR DESCRIPTION
**Pull request by seeker25**
https://github.com/bcgov/entity/issues/17493

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-account-dev--pr-2489-x4chpgn7.web.app

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-account-dev--pr-2489-x4chpgn7.web.app

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-account-dev--pr-2489-x4chpgn7.web.app

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-account-dev--pr-2489-x4chpgn7.web.app

**Comment by seeker25** [comment]
Can't reproduce unfortunately

**Pull request closed without merging**
