### PR TITLE
16624 Part 2 - Auth Web - Change NR/business action buttons

### PR DESCRIPTION
**Pull request by chenhongjing**
*Issue #:*
https://github.com/bcgov/entity/issues/16624

*Description of changes:*

- Resolved outstanding comments from https://github.com/bcgov/sbc-auth/pull/2422
- App version = 2.2.11

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

### CODE REVIEW

**Review by seeker25 — APPROVED** [review]

**Comment by seeker25** [comment]
as long as CI passes, 2 code smells should be fixed ideally (refactor into a function) - free to merge

**Review by severinbeauvais — APPROVED** [review]
LGTM.

Make sure the 2 keys you removed are still populated in temp URL, and later in Dev.

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-account-dev--pr-2433-timdhwu5.web.app

**Comment by severinbeauvais** [comment]
Hey, I noticed that some of the external links don't open in a new tab. They should. Can you fix that here?

**Comment by severinbeauvais** [comment]
I suspect UX Team will want some changes to some of the actions / behaviours. I highly recommend making those changes in a new ticket (not this one) -- we can't keep chasing a moving target (design).

**Comment by severinbeauvais** [comment]
I recommend a minimum height for the Type block so that the following BC Benefit Company is the same height as the other items.

image

**Comment by chenhongjing** [comment]
> Hey, I noticed that some of the external links don't open in a new tab. They should. Can you fix that here?

Can you tell me which one doesn't work correctly so that I can look into it

**Comment by severinbeauvais** [comment]
> > Hey, I noticed that some of the external links don't open in a new tab. They should. Can you fix that here?
> 
> Can you tell me which one doesn't work correctly so that I can look into it

Reinstate Now
Download Form
Register Now (in COLIN)
Continue In Now
Amalgamate Now
maybe others?

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-account-dev--pr-2433-timdhwu5.web.app

**Comment by severinbeauvais** [comment]
> > > Hey, I noticed that some of the external links don't open in a new tab. They should. Can you fix that here?
> > 
> > 
> > Can you tell me which one doesn't work correctly so that I can look into it
> 
> Reinstate Now Download Form Register Now (in COLIN) Continue In Now Amalgamate Now maybe others?

Looks good!

**Comment by severinbeauvais** [comment]
> LGTM.
> 
> Make sure the 2 keys you removed are still populated in temp URL, and later in Dev.

The external forms page loaded, so it looks like the keys are OK!

**Comment by severinbeauvais** [comment]
Hongjing, can I merge this PR now?

**Pull request merged**
