### PR TITLE
19026 - Implemented the number of businesses ready for D1 dissolution

### PR DESCRIPTION
**Pull request by JazzarKarim**
*Issue #:*
https://github.com/bcgov/entity/issues/19026

### ~Not merging and keeping it as draft for now. The PR endpoint is in review and hasn't been merged yet (https://github.com/bcgov/lear/pull/2683).~ _Should be fine now_
*Description of changes:*
- Implemented to show the number of businesses that are ready for D1 dissolution

endpoint

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-account-dev--pr-2831-22c0fofx.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-account-dev--pr-2831-22c0fofx.web.app

**Review by Jxio — APPROVED** [review]
LGTM

**Review by seeker25 — APPROVED** [review]
LGTM

**Pull request merged**
