### PR TITLE
24383 - Remove FAS-UI widget

### PR DESCRIPTION
**Pull request by seeker25**
*Issue #:*
https://github.com/bcgov/entity/issues/24383

*Description of changes:*
Remove FAS-UI widget

Use node 20.5.1

image

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-account-dev--pr-3146-t2bguhoj.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-account-dev--pr-3146-t2bguhoj.web.app

**Comment by seeker25** [comment]
@cameron-eyds redid this using Node 20.5.1, also updated a few files

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-account-dev--pr-3146-t2bguhoj.web.app

**Comment by cameron-eyds** [comment]
> @cameron-eyds redid this using Node 20.5.1, also updated a few files

Sounds great, thank you!

**Pull request merged**
