### PR TITLE
13152 Auth Web - Marketing Page Updates (More Tweaks)

### PR DESCRIPTION
**Pull request by lewischenstudio**
*Issue #:*
https://github.com/bcgov/entity/issues/13152

*Description of changes:*
- more text tweaks 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

### CODE REVIEW

**Review by seeker25 — APPROVED** [review]

**Review by lambert-alex — COMMENTED** [review]
LGTM!

**Review by lambert-alex — APPROVED** [review]

**Comment by lewischenstudio** [comment]
Thanks for the approvals. Can anyone merge this PR? Thanks!

**Comment by seeker25** [comment]
@lewischenstudio just tag me on here if you need a merge

**Comment by lewischenstudio** [comment]
Thank you for the merge Travis 👍 
Sure. I'll tag you in the future in need of a merge.

**Pull request merged**
