### PR TITLE
16622 - Updating business registry dashboard buttons, removing old code, adding unit tests

### PR DESCRIPTION
**Pull request by rodrigo-barraza**
*Issue #:*
https://github.com/bcgov/entity/issues/16622

*Description of changes:16622*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

### CODE REVIEW

**Comment by seeker25** [comment]
Ticket number not in the title

**Comment by seeker25** [comment]
still draft, but package + package-lock update please

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-account-dev--pr-2549-4uoxptwt.web.app

**Comment by seeker25** [comment]
This ticket looks fairly confusing I see a few different versions, thought this was the right one:

image

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-account-dev--pr-2549-4uoxptwt.web.app

**Review by seeker25 — APPROVED** [review]

**Pull request merged**
