### PR TITLE
remove rejected accounts from duplicate name search

### PR DESCRIPTION
**Pull request by kialj876**
Signed-off-by: Kial Jinnah <kialjinnah@gmail.com>

*Issue #:*
https://github.com/bcgov/entity/issues/11327

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

### CODE REVIEW

**Comment by kialj876** [comment]
... no idea why this is triggering all of the workflows...

**Comment by seeker25** [comment]
What about BCOL conflicts with rejected accounts?

**Comment by seeker25** [comment]
image

**Comment by kialj876** [comment]
> What about BCOL conflicts with rejected accounts?

Oh good point I missed that, thank you

**Review by seeker25 — APPROVED** [review]

**Pull request merged**
