### PR TITLE
15136 - Rename business-events-listener to namex-event-listener

### PR DESCRIPTION
**Pull request by seeker25**
https://github.com/bcgov/entity/issues/15136

*Description of changes:*
The old `business-events-listener` was listening from namex. It's been renamed to `names-events-listener`. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

### CODE REVIEW

**Comment by seeker25** [comment]
Test are failing.. because there are no tests.

**Comment by seeker25** [comment]
Ideally if we re-do the queues.. we can combine the projects and watch multiple queues at the same time hopefully. It will save a good 2000 lines of mostly duplicated code and maintenance.

**Review by kialj876 — APPROVED** [review]
I just did a pretty quick scan -- looks good to me. Can you add the devops folder into business-events-listener? I don't think Jia or Matthew will know to put that in

**Comment by seeker25** [comment]
I've removed the business-events-listener.  We wont be using it if we're calling directly into LEAR / NAMEX.

**Pull request merged**
