### PR TITLE
21948-Change-Continuation-Application

### PR DESCRIPTION
**Pull request by ArwenQin**
*Issue #:* bcgov/entity#21948

*Description of changes:*
- Updated "Continuation In" to "Continuation Application" in auth web UI

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

### CODE REVIEW

**Comment by ArwenQin** [comment]
Updated to Continuation Application, now looks like:
image

**Review by JazzarKarim — APPROVED** [review]
Looks good!

**Comment by JazzarKarim** [comment]
This change have been gone through by Andy and approved I assume right?

**Review by severinbeauvais — APPROVED** [review]
LGTM!

**Pull request merged**
