### PR TITLE
16960 - Auth Web: Affiliated Entity Table Filter Bug Fix

### PR DESCRIPTION
**Pull request by AbrahamRostampoor**
*Issue #:*
https://github.com/bcgov/entity/issues/16960

*Description of changes:*
In this pull request, I have implemented a fix for the column's filter in the affiliated entity table within the Auth Web application. The issue was related to incorrect filtering behaviour, and I have resolved it to ensure that the filters now work correctly.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-account-dev--pr-2552-9pm54fku.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-account-dev--pr-2552-9pm54fku.web.app

**Review by Jxio — APPROVED** [review]
Looks good to me, good job!

**Pull request merged**
