### PR TITLE
Changed wording for online banking payment method

### PR DESCRIPTION
**Pull request by hardikbcreg**
*Issue #:*
https://github.com/bcgov/entity/issues/15456

*Description of changes:*
Changed wording when client (with BASIC) with online banking payment method.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

### CODE REVIEW

**Comment by seeker25** [comment]
Update package.json, package-lock.json please

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-account-dev--pr-2322-zwbwov70.web.app

**Pull request merged**
