### PR TITLE
update sentry vue sdk version

### PR DESCRIPTION
**Pull request by bolyachevets**
*Issue #: [15861](https://github.com/bcgov/entity/issues/15861)

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-account-dev--pr-2326-cvze94bi.web.app

**Comment by seeker25** [comment]
Looks good to me
image

**Review by seeker25 — APPROVED** [review]

**Pull request merged**
