### PR TITLE
18319 - AUTH-WEB Updated corp-type-module version

### PR DESCRIPTION
**Pull request by AbrahamRostampoor**
*Issue #:*
https://github.com/bcgov/entity/issues/18319

*Description of changes:*
- Updated corp-type-module version 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

### CODE REVIEW

**Review by seeker25 — APPROVED** [review]

**Comment by seeker25** [comment]
package.json, package-lock.json versions please

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-account-dev--pr-2643-q2frn16i.web.app

**Pull request merged**
