### PR TITLE
Staff Task UXA + AccountStatus -> Comp Api

### PR DESCRIPTION
**Pull request by cameron-eyds**
*Issue #:*
https://github.com/bcgov/entity/issues/17242

*Description of changes:*
* Misc UXA updates as described in ticket ( Text Colour updates, text alignments, bit of formatting)
* Updates AccountStatus component to composition api

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-account-dev--pr-2541-xeux6fo9.web.app

**Review by seeker25 — APPROVED** [review]

**Comment by seeker25** [comment]
Cam, please put the ticket number in the title on each PR

**Comment by cameron-eyds** [comment]
> Cam, please put the ticket number in the title on each PR

Copy that, can do next time. Thank you for adding to this one 👍

**Pull request merged**
