### PR TITLE
update auth release to 2.10.2

### PR DESCRIPTION
**Pull request by avni-work**
*Issue #:*
https://github.com/bcgov/entity/issues/<Put the github issue number here>

*Description of changes:*
updating release version to 2.10.2

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

### CODE REVIEW

**Review by Jxio — APPROVED** [review]

**Review by seeker25 — APPROVED** [review]

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-account-dev--pr-2926-8kcz0k08.web.app

**Pull request merged**
