### PR TITLE
17029 - update sub-header text color

### PR DESCRIPTION
**Pull request by ketaki-deodhar**
*Issue #:*
https://github.com/bcgov/entity/issues/17029

*Description of changes:*

Fix based on Yui's observations.

Before:
image

After fix:
image

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-account-dev--pr-2498-68wauz19.web.app

**Review by seeker25 — APPROVED** [review]

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://bcregistry-account-dev--pr-2498-68wauz19.web.app

**Comment by seeker25** [comment]
LGTM, merge whenever

**Pull request merged**
