### PR TITLE
18100 - create notebook that adds flag and emails new EFT accounts

### PR DESCRIPTION
**Pull request by Jxio**
*Issue #:*
https://github.com/bcgov/entity/issues/18100
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

### CODE REVIEW

**Comment by seeker25** [comment]
Should be in the OPS repo, not the notebook job

**Review by seeker25 — CHANGES_REQUESTED** [review]
Should be in OPS repo not the public AUTH repo

**Comment by seeker25** [comment]
https://github.com/bcgov-registries/ops-support/tree/main/support/ops/accounts

**Comment by Jxio** [comment]
close this PR, move it to https://github.com/bcgov-registries/ops-support/pull/3261

**Pull request closed without merging**
