### PR TITLE
Minor tweak, when pasting in the same information as exists on the fi…

### PR DESCRIPTION
**Pull request by seeker25**
…eld.

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

### CODE REVIEW

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-account-dev--pr-2341-f4t1z2zp.web.app

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-account-dev--pr-2341-f4t1z2zp.web.app

**Comment by pwei1018** [comment]
Temporary Url for review: https://bcregistry-account-dev--pr-2341-f4t1z2zp.web.app

**Review by Jxio — APPROVED** [review]

**Pull request merged**
